#!/usr/bin/env bash

set -euo pipefail

CURDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
brewfile="${CURDIR}/Brewfile"

bundle() {
    brew bundle --file "${brewfile}" "${@:-}"
}

bundle check || bundle
