after-login-command = []
after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

# Keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
#
# Modifiers: cmd, alt, ctrl, shift
#
# Commands: https://nikitabobko.github.io/AeroSpace/commands
[mode.main.binding]
alt-tab      = 'workspace-back-and-forth'
alt-backtick = 'workspace-back-and-forth'

alt-j = 'focus --boundaries all-monitors-outer-frame down'
alt-k = 'focus --boundaries all-monitors-outer-frame up'
alt-h = 'focus --boundaries all-monitors-outer-frame left'
alt-l = 'focus --boundaries all-monitors-outer-frame right'

alt-shift-j = 'join-with down'
alt-shift-k = 'join-with up'
alt-shift-h = 'join-with left'
alt-shift-l = 'join-with right'

alt-shift-ctrl-j = 'move down'
alt-shift-ctrl-k = 'move up'
alt-shift-ctrl-h = 'move left'
alt-shift-ctrl-l = 'move right'

alt-shift-f = 'fullscreen'
alt-shift-space = 'layout floating tiling'

alt-shift-s = 'layout v_accordion' # stacking
alt-shift-t = 'layout h_accordion' # tabbed
alt-shift-e = 'layout tiles horizontal vertical' # toggle split
alt-shift-v = 'layout tiles vertical'
alt-shift-z = 'layout tiles horizontal'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-leftSquareBracket =  'workspace prev'
alt-rightSquareBracket = 'workspace next'

alt-shift-1 = ['move-node-to-workspace  1', 'workspace  1']
alt-shift-2 = ['move-node-to-workspace  2', 'workspace  2']
alt-shift-3 = ['move-node-to-workspace  3', 'workspace  3']
alt-shift-4 = ['move-node-to-workspace  4', 'workspace  4']
alt-shift-5 = ['move-node-to-workspace  5', 'workspace  5']
alt-shift-6 = ['move-node-to-workspace  6', 'workspace  6']
alt-shift-7 = ['move-node-to-workspace  7', 'workspace  7']
alt-shift-8 = ['move-node-to-workspace  8', 'workspace  8']
alt-shift-9 = ['move-node-to-workspace  9', 'workspace  9']
alt-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

alt-comma  = 'focus-monitor prev'
alt-period = 'focus-monitor next'

alt-shift-comma  = 'move-workspace-to-monitor prev'
alt-shift-period = 'move-workspace-to-monitor next'

alt-shift-r = 'mode resize'

# -n: Always open a new instance because I want it to open in my home directory.
alt-enter = 'exec-and-forget open -n /Applications/Alacritty.app'

alt-shift-x = 'exec-and-forget sh -c ~/bin/pbclear'

[mode.resize.binding]
j = 'resize height +50'
k = 'resize height -50'
h = 'resize width -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
6  = 'Built-in Retina Display'
7  = [3, 'main']
8  = [3, 'main']
9  = [3, 'main']
10 = [3, 'main']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.linear'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace 10'
