#!/bin/sh

bspc config border_width 0
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config click_to_focus true

bspc config initial_polarity second_child
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -r *:*
bspc rule -a Gimp state=floating
bspc rule -a Slack desktop='^8'
bspc rule -a TelegramDesktop desktop='^7'
bspc rule -a Liferea desktop='^6'

pulseaudio --check || pulseaudio
nitrogen --restore &
redshift &
ps -u jdkaplan | grep -oq panel && pkill panel; $XDG_CONFIG_HOME/panel/panel &

qutebrowser &
telegram-desktop &
slack &
