#!/bin/sh

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

bspc config initial_polarity second_child

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

echo 'xss-lock'
xss-lock -- i3lock -e -i ~/images/lockscreen.png &
echo 'nitrogen'
nitrogen --restore &
echo 'panel'
$PANEL_CONFIG_DIR/panel &
