#!/bin/sh

bspc config border_width 0
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

bspc config initial_polarity second_child
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Gimp state=floating
bspc rule -a Slack desktop='^8'
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external_rules"

pulseaudio --check || pulseaudio
ps -u jdkaplan | grep -o xss-lock || xss-lock -- i3lock -e -i ~/images/lockscreen.png &
nitrogen --restore &
ps -u jdkaplan | grep -o panel && pkill panel; $XDG_CONFIG_HOME/panel/panel &
