#!/usr/bin/env bash

set -exuo pipefail

VENV="~/.virtualenvs/neovim3"
PYTHON="${VENV}/bin/python"

if [ -d "${VENV}" ]; then
    # Upgrade the venv if the global Python version has changed.
    local_py=$("${PYTHON}" --version)
    global_py=$(python3 --version)
    if [ "${local_py}" != "${global_py}" ]; then
        python3 -m venv --upgrade "${VENV}"
        "${PYTHON}" -m pip install --upgrade pip
    fi
else
    python3 -m venv "${VENV}"
fi

"${PYTHON}" -c 'import pynvim' || "${PYTHON}" -m pip install pynvim
