defaults:
  prsLimit: 20
  issuesLimit: 20
  preview:
    open: true
    width: 100

prSections:
  - title: My PRs
    filters: is:open author:@me
  - title: To Review
    filters: is:open review-requested:@me

issuesSections:
  - title: Assigned
    filters: is:open assignee:@me
