(deftheme jdkaplan "jdkaplan's theme")
(custom-theme-set-faces
 'jdkaplan
 '(default ((t (:foreground "#e4e4e4" :background "#262626" ))))
 '(cursor ((t (:background "#eeeeee" ))))
 '(fringe ((t (:background "#262626" ))))
 '(mode-line ((t (:foreground "#eeeeee" :background "#444444" ))))
 '(mode-line-inactive ((t (:foreground "#444444" :background "#1e1e1e" ))))
 '(vertical-border ((t (:foreground "#444444" :background "#262626" ))))
 '(region ((t (:background "#3a3a3a" ))))
 '(secondary-selection ((t (:background "#1e1e1e" ))))
 '(font-lock-builtin-face ((t (:foreground "#f67f4e" ))))
 '(font-lock-comment-face ((t (:foreground "#aaaaaa" ))))
 '(font-lock-function-name-face ((t (:foreground "#00c7ff" ))))
 '(font-lock-keyword-face ((t (:foreground "#3cc93a" ))))
 '(font-lock-string-face ((t (:foreground "#d4a102" ))))
 '(font-lock-type-face ((t (:foreground "#e8cf0e" ))))
 '(font-lock-constant-face ((t (:foreground "#b987ff" ))))
 '(font-lock-variable-name-face ((t (:foreground "#00c7ff" ))))
 '(minibuffer-prompt ((t (:foreground "#c7c7c7" :bold t ))))
 '(font-lock-warning-face ((t (:foreground "red" :bold t ))))

 '(show-paren-match-face ((t (:foreground "orange" :background "black" :bold t))))
 )

(provide-theme 'jdkaplan)
