(deftheme jdkaplan-light "jdkaplan's light theme")

(let (
      (black "#1e1e1e")
      (lightblack "#262626")
      (darkgray "#3a3a3a")
      (gray "#444444")
      (lightgray "#aaaaaa")
      (lightergray "#c7c7c7")
      (darkwhite "#e4e4e4")
      (white "#eeeeee")

      (red "#ab4642")
      (lightorange "#dc9656")
      (orange "#f67f4e")
      (goldenrod "#ccac62")
      (paleyellow "#f7ca88")
      (yellow "#e0d000")
      (lime "#38ce35")
      (palegreen "#a1d06c")
      (darkpalegreen "#00a37a")
      (green "#00a000")
      (seagreen "#04d4a0")
      (teal "#3ecae0")
      (brightblue "#00c7ff")
      (paleblue "#66C4FF")
      (bluegray "#8bcef0")
      (darkbluegray "#4c90b2")
      (blue "#027cc9")
      (purple "#b98fff")
      (darkpurple "#7e2ffc")
      (tan "#d49804")
      (brown "#a87f00")
      (neutralbrown "#c78f6b")
      )

  (send-string-to-terminal "\033]11;white\007")
  (send-string-to-terminal "\033]12;black\007")

  (custom-theme-set-faces
   'jdkaplan-light
   `(default ((t (:foreground ,lightblack :background ,darkwhite ))))
   `(cursor ((t (:background ,black :foreground ,white ))))
   `(fringe ((t (:background ,darkwhite ))))
   `(mode-line ((t (:foreground ,black :background ,lightgray ))))
   `(mode-line-inactive ((t (:foreground ,lightgray :background ,white ))))
   `(vertical-border ((t (:foreground ,lightgray :background ,darkwhite ))))
   `(region ((t (:background ,lightergray ))))
   `(secondary-selection ((t (:background ,white ))))
   `(font-lock-builtin-face ((t (:foreground ,lightorange ))))
   `(font-lock-comment-face ((t (:foreground ,lightgray ))))
   `(font-lock-function-name-face ((t (:foreground ,blue ))))
   `(font-lock-keyword-face ((t (:foreground ,green ))))
   `(font-lock-string-face ((t (:foreground ,tan ))))
   `(font-lock-type-face ((t (:foreground ,brown ))))
   `(font-lock-constant-face ((t (:foreground ,darkpurple ))))
   `(font-lock-variable-name-face ((t (:foreground ,blue ))))
   `(minibuffer-prompt ((t (:foreground ,gray :bold t ))))
   `(font-lock-warning-face ((t (:foreground ,red :bold t ))))
   `(hl-line ((t (:background "gray80"))))

   `(web-mode-html-attr-name-face ((t (:foreground ,darkpalegreen ))))
   `(web-mode-html-attr-equal-face ((t (:foreground "gray30" ))))
   `(web-mode-html-tag-bracket-face ((t (:foreground "gray30" ))))
   `(web-mode-html-tag-face ((t (:foreground ,darkbluegray :bold t ))))
   `(web-mode-block-delimiter-face ((t (:foreground ,orange ))))

   `(show-paren-match-face ((t (:foreground ,teal :bold t ))))
   )
  )

(provide-theme 'jdkaplan-light)
